name: Build Radial Menu Builder

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - platform: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
            artifact-name: radial-menu-builder-linux
            bundle-path: src-tauri/target/release/bundle/appimage/*.AppImage
          - platform: windows-latest
            rust-target: x86_64-pc-windows-msvc
            artifact-name: radial-menu-builder-windows
            bundle-path: src-tauri/target/release/bundle/msi/*.msi
          - platform: macos-latest
            rust-target: x86_64-apple-darwin
            artifact-name: radial-menu-builder-macos
            bundle-path: src-tauri/target/release/bundle/macos/*.app

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust-target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend
        run: npm run build-frontend

      - name: Build Tauri app
        run: npm run build

      - name: Create distribution package (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir RadialMenuBuilder
          copy "src-tauri\target\release\radial-menu-builder.exe" "RadialMenuBuilder\"
          copy "dist\commands.json" "RadialMenuBuilder\"
          echo "Radial Menu Builder - Edit commands.json to customize available commands" > RadialMenuBuilder\README.txt
        shell: cmd

      - name: Create distribution package (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          mkdir RadialMenuBuilder
          cp src-tauri/target/release/radial-menu-builder RadialMenuBuilder/
          cp dist/commands.json RadialMenuBuilder/
          echo "Radial Menu Builder - Edit commands.json to customize available commands" > RadialMenuBuilder/README.txt

      - name: Create distribution package (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir RadialMenuBuilder
          cp -r src-tauri/target/release/bundle/macos/*.app RadialMenuBuilder/
          cp dist/commands.json RadialMenuBuilder/
          echo "Radial Menu Builder - Edit commands.json to customize available commands" > RadialMenuBuilder/README.txt

      - name: Archive Windows build
        if: matrix.platform == 'windows-latest'
        run: |
          Compress-Archive -Path "RadialMenuBuilder\*" -DestinationPath "radial-menu-builder-windows.zip"
        shell: powershell

      - name: Archive Linux build
        if: matrix.platform == 'ubuntu-latest'
        run: |
          tar -czf radial-menu-builder-linux.tar.gz RadialMenuBuilder/

      - name: Archive macOS build
        if: matrix.platform == 'macos-latest'
        run: |
          tar -czf radial-menu-builder-macos.tar.gz RadialMenuBuilder/

      - name: Upload Windows artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: radial-menu-builder-windows
          path: radial-menu-builder-windows.zip

      - name: Upload Linux artifact
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: radial-menu-builder-linux
          path: radial-menu-builder-linux.tar.gz

      - name: Upload macOS artifact
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: radial-menu-builder-macos
          path: radial-menu-builder-macos.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            plasticity-radial-menu-builder-windows/plasticity-radial-menu-builder-windows.zip
            plasticity-radial-menu-builder-linux/plasticity-radial-menu-builder-linux.tar.gz
            plasticity-radial-menu-builder-macos/plasticity-radial-menu-builder-macos.tar.gz
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
